### ISSUE TITLE
Opaqueness of user role manager chat setting

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ijwfly/chatgpt-tg#15]
Hey. I've figured out how most of the settings works, except those ones:

```py
# Enables chat for user role management
# When enabled sends new user info to USER_ROLE_MANAGER_CHAT_ID with keyboard to choose user role
ENABLE_USER_ROLE_MANAGER_CHAT = False
USER_ROLE_MANAGER_CHAT_ID = -1
```

I'm struggling to figure out both (1) their purpose and (2) what exact ID does `USER_ROLE_MANAGER_CHAT_ID` expecting to be provided, because no matter what I put there it throws the exact same "unable to find chat" error.

**Comment by ijwfly** [comment]
This feature is currently undocumented, yes. You can enable it, and the bot will send you management messages in the chat when a new user writes to the bot.
![image](https://github.com/ijwfly/chatgpt-tg/assets/6737509/4d263250-7f74-40ce-abb1-d2c42e8a4ba2)

You can use the buttons in this message to manage the roles of new users. The USER_ROLE_MANAGER_CHAT_ID setting can contain either your personal Telegram ID or the ID of a group chat that you want to use as a chat for administering the bot.

Additionally, the bot will send statistics to this chat at the beginning of each new month regarding the consumption of all users for the past month.

**Comment by yaroslavyaroslav** [comment]
Thanks, what about the roles themselves? What's standing behind the each of them?

**Comment by ijwfly** [comment]
The idea of the role model is that users, when they come to the bot, receive a default role. Which role is considered default can be set in settings.py. The bot administrator can assign them a different role, depending on which certain functionalities in the bot will be available or unavailable to users.
Roles have several levels, currently there are four: stranger, basic, advanced, and admin. Each subsequent role is, in a way, higher than the previous one. The settings in settings.py determine the minimum necessary role for access to the functionality.

Overall, the bot administrator decides what each role represents. They have the option to give users with the default role access to all features or to restrict access heavily and divide the features between admins, basic users, and advanced users.

**Comment by yaroslavyaroslav** [comment]
Yep that helped, thanks
