### ISSUE TITLE
Wolfram integration issue

### ISSUE THREAD

**Issue by yaroslavyaroslav** [ijwfly/chatgpt-tg#16]
I'm struggling to get to work wolfram alpha integration here. 

I've set it up like this and yet it doesn't seems like gpt reaches it in any case? What're the limitation of such plugin and use cases?

```py
# Plugins settings
ENABLE_WOLFRAMALPHA = True
WOLFRAMALPHA_APPID = 'some app ID'
```

**Comment by ijwfly** [comment]
You can ask it about weather or about currencies. Or some random facts with numbers like population of Great Britain. There is a setting in Settings menu "Verbose function calls", that will show calls to wolframalpha and their results.
Also you can directly ask model to use wolframalpha to get info, like "Ask wolfram about current weather in New York", sometimes it is useful.

P.S. I dunno why, but gpt-4-vision [doesn't support](https://community.openai.com/t/does-the-model-gpt-4-vision-preview-have-function-calling/490197/2) function calling for now. You must use other models for wolframalpha to work for now.

**Comment by yaroslavyaroslav** [comment]
It's wired, it doesn't work in my case. 

![image](https://github.com/ijwfly/chatgpt-tg/assets/16612247/abb1cd90-294f-4956-b157-f3c507de5307)

**Comment by ijwfly** [comment]
On screenshot It says your model is `gpt-4-vision-preview` and you have no permissions to change the model. Your role must be higher than role you set up in `USER_ROLE_CHOOSE_MODEL` variable.

**Comment by yaroslavyaroslav** [comment]
> On screenshot It says your model is `gpt-4-vision-preview` and you have no permissions to change the model. Your role must be higher than role you set up in `USER_ROLE_CHOOSE_MODEL` variable.

Yep, I've deleted the screenshot because I'd found this exact warning by myself. And this leads to a question: how can I reset db or how can I rewrite the permissions of the chat ID provided in the settings app as an admin to, well, actually admin? Because it seems that it treats this chat as under ruled one even though it actually rules the permission of others chats

**Comment by ijwfly** [comment]
You can try:
`docker-compose exec postgres psql -U postgres -d chatgpttg -c "UPDATE chatgpttg.user SET role='admin' WHERE telegram_id={YOUR_TELEGRAM_ID};"`

The password is `password`

**Comment by ijwfly** [comment]
I've updated setup instructions [here](https://github.com/ijwfly/chatgpt-tg/tree/feature/dalle-3) and settings order in `settings.py`.  Maybe it will be easier to install and configure bot for new users.

**Comment by yaroslavyaroslav** [comment]
Doesn't affects anything. It's getting even worst actually, coz now menu options to change a model disappeared in each of my account 💁🏻‍♂️

FYI: This line that I've run as follows didn't requests a password prompt.

`docker-compose exec postgres psql -U postgres -d chatgpttg -c "UPDATE chatgpttg.user SET role='admin' WHERE telegram_id={11111111111111};"`

**Comment by ijwfly** [comment]
The correct syntax is:
`docker-compose exec postgres psql -U postgres -d chatgpttg -c "UPDATE chatgpttg.user SET role='admin' WHERE telegram_id=11111111111111;"`
You don't need curved bracers for telegram_id in this query. 

> now menu options to change a model disappeared in each of my accounts 💁🏻‍♂️

You changed roles, and your accounts now haven't got an option to change model. You can update roles for your accounts from management messages or via sql query. After that do docker-compose restart, it will restart update_keyboards scipt and the script will update keyboards to your current role state.

**Comment by yaroslavyaroslav** [comment]
Yep, it worked this way, thanks, and wolfram is works as expected now.
