### ISSUE TITLE
If message exceed 4096 chars, it will break the bot

### ISSUE THREAD

**Issue by KenKout** [ijwfly/chatgpt-tg#19]
https://stackoverflow.com/questions/70819525/send-long-message-in-telegram-bot-python
I have some issues with the bot when ChatGPT sends a long message. I think you should improve this code for better performance

**Comment by ijwfly** [comment]
Hello! Could you provide me with some details about your setup? Have you installed the latest version of the bot? I resolved this issue on [November 14th](https://github.com/ijwfly/chatgpt-tg/commit/6c18f4d165352b3028eb26692ffff774cfedcfe2). If your installation includes these fixes, could you please describe your situation?

**Comment by KenKout** [comment]
Oh, I thought it was caused by the limitation. Sometime the bot just suddenly stop working when it's typing. Sorry for wasting your time. But can you add a function to send long message ? Since when I send over 4089 chars, it will break into many message and the bot doesn't understand. 
Anyways, thank you for creating such a good bot

**Comment by ijwfly** [comment]
Sometimes, the OpenAI API will timeout. By default, its timeout setting is configured for 10 minutes, with 2 retries, totaling a potential wait time of 30 minutes. However, if 30 minutes have elapsed, you would typically receive a TimeoutError message from the bot.

Also, I've [already implemented](https://github.com/ijwfly/chatgpt-tg/commit/349815bb6f367d56b105ead3ae4eaa3efe2268e7) batch handling. Your specific use case, involving 4096 characters, is now fully supported. Messages exceeding 4096 characters can be sent to the bot; the client will divide them into multiple messages. The bot will then consolidate these segments into single batch and process them as a single message.

So, I recommend you to update to the latest version of the code.

**Comment by KenKout** [comment]
Hi, I have updated to the latest one. Once again thank you for creating such a good bot. Wish you all the best.
